"""initial schema

Revision ID: ceb82ba90f94
Revises: 
Create Date: 2026-08-05 08:15:01.116714
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ceb82ba90f94'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ticker_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolve_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buy_threshold_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sell_threshold_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('resolution_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('winning_outcome', sa.String(length=10), nullable=True),
    sa.Column('notional_krw', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_fund_id'), 'markets', ['fund_id'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_index(op.f('ix_markets_ticker'), 'markets', ['ticker'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ticker_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'ticker', name='uq_position_fund_ticker')
    )
    op.create_index(op.f('ix_positions_fund_id'), 'positions', ['fund_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('stake', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('payout', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'member_id', 'outcome', name='uq_bet_market_member_outcome')
    )
    op.create_index(op.f('ix_bets_market_id'), 'bets', ['market_id'], unique=False)
    op.create_index(op.f('ix_bets_member_id'), 'bets', ['member_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_market_id'), 'ledger_entries', ['market_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_member_id'), 'ledger_entries', ['member_id'], unique=False)
    op.create_table('trade_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('total_stake', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_decisions_market_id'), 'trade_decisions', ['market_id'], unique=False)
    op.create_index(op.f('ix_trade_decisions_status'), 'trade_decisions', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('broker_env', sa.String(length=10), nullable=False),
    sa.Column('broker_order_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['trade_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_no'), 'orders', ['broker_order_no'], unique=False)
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_fund_id'), 'orders', ['fund_id'], unique=False)
    op.create_index(op.f('ix_orders_market_id'), 'orders', ['market_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_market_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_fund_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trade_decisions_status'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_market_id'), table_name='trade_decisions')
    op.drop_table('trade_decisions')
    op.drop_index(op.f('ix_ledger_entries_member_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_market_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_bets_member_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_market_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_positions_fund_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_markets_ticker'), table_name='markets')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_fund_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_table('funds')
    # ### end Alembic commands ###
